### ISSUE TITLE
Audio not playing on some Android devices

### ISSUE THREAD

**Issue by asavardplante** [react-native-community/react-native-audio-toolkit#196]
After some tweaking to add the library to my project, I finally managed to make the player plays my record. Everything works fine, except that on some **android** device (LG G4, Android 6.0) The player won't play any sound. It works fine on my colleague's device ( which are also androids) and every iOS devices, but for some Android, it doesn't... 

**Any idea/solution to fix this problem?**

I already tried @xstable branch, but the problem still persists 🤔

**Comment by xstable** [comment]
You'd better link my ticket, so the people knows what you talking about: 

https://github.com/react-native-community/react-native-audio-toolkit/issues/149

You've noticed, that there was a little issue in my answer? In the second code-script, you have to choose **aac-lc** for sure, I had there only **aac** (now I fixed it).

![image](https://user-images.githubusercontent.com/1778068/75029696-da2c6880-54a2-11ea-9d25-b4841b5a1591.png)

**Comment by asavardplante** [comment]
Sadly it still doesn't work even with your fix, but what I notice is that the state on the devices that won't play sound returns `state: -1`

**Comment by chj-damon** [comment]
any update? I found it doesn't work on Huawei devices.

**Comment by nikiyasimpson** [comment]
Also looking for any answers to this. I've made the above change. It looks like it is recording and records the length of the sound byte but no sound is on the file.

**Comment by chj-damon** [comment]
@xstable you are recording, but we are playing... maybe they are different?

**Comment by nikiyasimpson** [comment]
I can record and play on iOS device. On Android, the file plays but there is no sound. I think it has recorded something based on the length of the audio file but when I listen to it, there is nothing.

**Comment by CoSNaYe** [comment]
I also encounter the audio playing issue on some Android devices. After rolling out my new version of app with this library, there're some users started to complain that audio play is broken.

**Comment by ykcadcg** [comment]
same her even with emulator, seems playing but no voice

**Comment by ykcadcg** [comment]
Any update on how to fix/ workaround? Urgent, thanks~

**Comment by nikbelikov** [comment]
Same problem here

**Comment by klaaz0r** [comment]
I also have this problem, `state: -1` nothing seems to work on android

**Comment by hussainarthuna** [comment]
I have the same problem. Please help.
iOS works perfectly but for android, the prepare is not working at all. No callback.

**Comment by krean93** [comment]
I have the same problem for Huawei phones.

**Comment by jimtang9527** [comment]
使用react-native-video可解决问题

**Comment by ksoghoyan** [comment]
I have the same problem for Huawei and HTC phones.

**Comment by superplussed** [comment]
Any updates on this?

**Comment by oshri-humanz** [comment]
> I have the same problem. Please help.
> iOS works perfectly but for android, the prepare is not working at all. No callback.

Same problem on all android phones. 
Any solution?

**Comment by kidequinox** [comment]
Prepare is working for me when file is local.
But prepare is not working and causing errors when audio file is remote. When I updated **shouldUpdateProgressBar** remote files worked again for me:

shouldUpdateProgressBar() {
    return this.player && this.player.duration >= 0 && Date.now() - this.lastSeek > 200;
 }
